# fly.toml app configuration file generated for nat-park-backend on 2024-03-27T21:02:42-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nat-park-backend'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
